blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/DooDesch/TarkovPilotSync#readme
    about: Read the documentation before creating an issue
  - name: ðŸ’¬ Discussions
    url: https://github.com/DooDesch/TarkovPilotSync/discussions
    about: Ask questions and discuss features

